package tqs.AirQuality;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class TestInterface {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void testInterface() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(840, 730));
    driver.findElement(By.id("latID")).click();
    driver.findElement(By.id("latID")).sendKeys("40.4");
    driver.findElement(By.id("lonID")).click();
    driver.findElement(By.id("lonID")).sendKeys("-8.5");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".col-12:nth-child(4) > .btn")).click();

    assertThat(driver.findElement(By.id("latID1")).getText(), is(""));
    assertThat(driver.findElement(By.id("lonID1")).getText(), is(""));

    driver.findElement(By.id("latID1")).click();
    driver.findElement(By.id("latID1")).sendKeys("37.6");
    driver.findElement(By.id("lonID1")).click();
    driver.findElement(By.id("lonID1")).sendKeys("-9.6");
    driver.findElement(By.cssSelector(".col-12:nth-child(3) > .btn")).click();
    driver.findElement(By.cssSelector("span:nth-child(1)")).click();
    driver.findElement(By.cssSelector("span:nth-child(1)")).click();

    {
      WebElement element = driver.findElement(By.cssSelector("span:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    assertThat(driver.findElement(By.cssSelector("h3 > b")).getText(), is("City: Sines"));
    assertThat(driver.findElement(By.id("latID1")).getText(), is(not("37.6")));
    assertThat(driver.findElement(By.id("lonID1")).getText(), is(not("-9.6")));
  }
}
