package tqs.Air_Quality;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


class TestInterfaceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  void testInterface() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(857, 727));
    driver.findElement(By.id("latID")).click();
    driver.findElement(By.id("latID")).click();
    driver.findElement(By.id("latID")).sendKeys("40.456");
    driver.findElement(By.id("lonID")).click();
    driver.findElement(By.id("lonID")).sendKeys("-8.534");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}